### ISSUE TITLE
./corewar don't check the extension file .cor

### ISSUE THREAD

**Issue by tlenglin** [emilwallner/Corewar#11]

**Comment by emilwallner** [comment]
@Natansab What's your take on this?

**Comment by Natansab** [comment]
> 	if (ft_strlen(e->files[e->player[i].file_pos]) <= 4 ||
> 				strcmp(e->files[e->player[i].file_pos] +
> 						ft_strlen(e->files[e->player[i].file_pos]) - 4,".cor"))
> 		ft_exit(e, 11);

code to check if .cor file
@emilwallner
