### ISSUE TITLE
./corewar doesn't quit correctly

### ISSUE THREAD

**Issue by tlenglin** [emilwallner/Corewar#15]
if only player 1 live and not the other the vm is still running (but quit correctly if no player live)

**Comment by tlenglin** [comment]
it will probably be fix in the same time but a player should disappear when he is not live anymore, and only when there is only one last contestant the program quit

**Comment by emilwallner** [comment]
It's cool, the cursors have their own lives. The game is over when no one has registered a life in the life to die cycle.
